export enum Status {
    NEW = 'NEW',
    READY_FOR_DEVELOPMENT = 'READY_FOR_DEVELOPMENT',
    IN_DEVELOPMENT = 'IN_DEVELOPMENT',
    CORE_REVIEW = 'CORE_REVIEW',
    READY_FOR_TESTING = 'READY_FOR_TESTING',
    IN_TEST = 'IN_TEST',
    READY_FOR_REVIEW = 'READY_FOR_REVIEW',
    ACCEPTED = 'ACCEPTED',
    REJECTED = 'REJECTED',
    PENDING = 'PENDING'
}